name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-image:
    name: Build Image
    uses: ./.github/workflows/build-image.yml

  list-flows:
    needs: build-image
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: src/{flows/**/*_flow.py,deployments/**/*_deployment.py}
          json: true

      - id: set-matrix  # Get changed files and replace "flows" with "deployment" and deduplicate
        run: |
          matrix=${{ steps.changed-files.outputs.all_changed_files }}
          matrix=$(echo $matrix | jq 'map(gsub("flows"; "deployments") | gsub("_flow"; "_deployment")) | unique' | jq -c '.')  # Compact JSON
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  deploy-flows:
    needs: list-flows
    if: ${{ needs.list-flows.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flows: ${{ fromJson(needs.list-flows.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: flow  # example output: "src/deployments/sample/hello_world_deployment.py"
        run: |
          echo "flow_python_path=${{ matrix.flows }}" >> $GITHUB_OUTPUT

      - id: deploy
        uses: ./.github/actions/deploy-flow
        with:
          prefect_api_key: ${{ secrets.PREFECT_TOKEN }}
          flow_python_path: ${{ steps.flow.outputs.flow_python_path }}
